"""Write the two files that give the embedded runtime its import path.

Python's embeddable distribution resolves imports from `python3xx._pth`
and from nothing else. When that file is present the interpreter ignores
the registry, ignores `PYTHONHOME`, and — the part that matters here —
**ignores `PYTHONPATH`**. Both consequences need answering, and they need
different answers.

**The twelve source roots go in `._pth`.** They are read out of
`pyproject.toml`, which is the one place this project declares them.
Three hand-maintained copies of that list already exist (the pytest
config, `scripts/dev_stack.sh`, `alembic.ini`) and one of them has
already drifted — `packages/decision` was added for the suite and not
for the server, and 2277 tests passed against an API that could not
boot. Generating the fourth copy rather than writing it is how this one
stays honest.

**`PYTHONPATH` gets handed back by `sitecustomize.py`.** The plugin
subprocess lane passes an imported algorithm's location to its worker
through that variable (`subprocess_lane.py:_environment`), so an
interpreter that ignores it starts a worker that cannot import the
plugin it was started for — and the failure surfaces as a worker that
dies on every tick, which the host reads as an algorithm that stops the
robot. `sitecustomize` runs on every interpreter startup, including
every subprocess, which is exactly the scope needed.
"""

from __future__ import annotations

import argparse
import sys
import tomllib
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]

#: On pytest's path and deliberately not on the application's. Kept
#: identical to `scripts/serve.py` and `planbench_desktop.bootstrap`.
TEST_ONLY = frozenset({".", "tests"})

SITECUSTOMIZE = '''\
"""Give PYTHONPATH back to an embedded interpreter that ignores it.

Generated by scripts/desktop/make_runtime_paths.py — do not edit here.

An embeddable Python with a `._pth` file resolves `sys.path` from that
file alone. That is what puts this application's source roots on the
path, and it also silently drops `PYTHONPATH` — which the plugin
subprocess lane uses to tell its worker where an imported algorithm
lives. Without this the worker starts, fails to import the plugin, and
the host sees an algorithm that halts the robot on every tick rather
than a path problem.
"""

import os
import sys

for _entry in os.environ.get("PYTHONPATH", "").split(os.pathsep):
    if _entry and _entry not in sys.path:
        sys.path.insert(0, _entry)
'''


def source_roots() -> list[str]:
    """The package roots, relative, in declaration order."""
    config = tomllib.loads((REPO_ROOT / "pyproject.toml").read_text(encoding="utf-8"))
    declared = config["tool"]["pytest"]["ini_options"]["pythonpath"]
    return [entry for entry in declared if entry not in TEST_ONLY]


def pth_contents(python_tag: str) -> str:
    """The `._pth` body, with the source roots relative to `runtime\\`.

    `import site` is not optional. Without it `site` never runs, and
    `.pth` files inside `site-packages` — which several installed
    distributions rely on — are never processed, along with
    `sitecustomize` itself.
    """
    lines = [f"{python_tag}.zip", ".", "Lib\\site-packages"]
    lines += [f"..\\app\\{root.replace('/', chr(92))}" for root in source_roots()]
    lines.append("")
    lines.append("import site")
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("runtime", type=Path, help="the staged runtime directory")
    parser.add_argument(
        "--python-tag",
        default="python312",
        help="the interpreter's tag, e.g. python312 (names the ._pth and the stdlib zip)",
    )
    args = parser.parse_args(argv)

    runtime: Path = args.runtime
    if not runtime.is_dir():
        print(f"not a directory: {runtime}", file=sys.stderr)
        return 1

    pth = runtime / f"{args.python_tag}._pth"
    pth.write_text(pth_contents(args.python_tag), encoding="utf-8")

    site_packages = runtime / "Lib" / "site-packages"
    site_packages.mkdir(parents=True, exist_ok=True)
    (site_packages / "sitecustomize.py").write_text(SITECUSTOMIZE, encoding="utf-8")

    print(f"wrote {pth.name} with {len(source_roots())} source roots")
    print(f"wrote {site_packages.name}/sitecustomize.py")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
